// Defines the status of a suggestion
export enum SuggestionStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
}

// Represents a suggestion object
export interface Suggestion {
  id: string;         // Unique identifier, generated by the backend
  text: string;       // The content of the suggestion
  status: SuggestionStatus; // Current status of the suggestion
  submittedAt: number; // Unix timestamp (in milliseconds) when the suggestion was submitted
}

// (Optional) Type for the admin user/token payload if needed later for JWT
// export interface AdminUser {
//   id: string; // or username, etc.
//   role: 'admin';
// }
